export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'; //loading
export const SOME_NAME_lIST = 'SOME_NAME_lIST'; //白名单
export const SOME_newStageInfo_List = 'SOME_newStageInfo_List'; //里程碑保存
export const SOME_searchData_List = 'SOME_searchData_List'; //里程碑保存
export const SOME_Popup_List = 'SOME_Popup_List'; //是否滑动保存
export const GET_projectMessage_DATA = 'GET_projectMessage_DATA'; //projectId
export const GET_selectedMan_DATA = 'GET_selectedMan_DATA'; //选中 @人
export const GET_selectedList_DATA = 'GET_selectedList_DATA'; //选中 @人
export const GET_dynamicDetail_DATA = 'GET_dynamicDetail_DATA'; //反馈
export const SET_CURSOR_DATA = 'SET_CURSOR_DATA'; //光标的位置
export const SET_projectHead_Info = 'SET_projectHead_Info'; //专案头部信息userInfo
export const GET_user_Info = 'GET_user_Info'; //用户信息
export const SET_userStatistics_Info = 'SET_userStatistics_Info'; //用户信息
export const GET_version_Info = 'GET_version_Info'; //用户信息
export const GET_from_Info = 'GET_from_Info';  //智慧工厂带过来的信息
export const GET_token_Info = 'GET_token_Info';  //token
