//  网络请求通用部分
export default {
  url: "",
  method: "GET",
  data: {},
  headers: {

    // "Authorization": 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InJlYWxOYW1lIjoi5buW5b-X5YiaIiwibG9naW5OYW1lIjoiQ1c1MTc5IiwidXNlcklkIjo2MjA1NDZ9LCJzdWIiOiIxNTEzMjE0MTc4ODM2IiwiaXNzIjoiY2V3YXkxMDAwIiwiYXVkIjoiVkpQWFVIVXF5MENVNEdWMGdjenFFakRCTlNTZFpXZlJpdEJkQ0pqaGNVVTBlcUdTNU5nYTBDSHFEZDFrUE9JWiJ9.mXispiXWSQp47tWgYXb0swYXNg_lmOi8iCaIlPbVPas',

    "Authorization": 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjp7InJlYWxOYW1lIjoi5p2o5LmQIiwibG9naW5OYW1lIjoiQ1c1MzIwIiwidXNlcklkIjoiMjM4NGVjOTVmZGNkNDJjYzkyOWVkZDI1MTJlNDdlODgifSwic3ViIjoiMTUxOTQ2NTMyNDMzNSIsImlzcyI6InRlc3QtaW1jbG91ZC1mV2U1eiIsImF1ZCI6ImVvZDQ3RW9FVm5ZdkZ3djBxdGpTWVVxZU5saHhjZGxqRW94Z3ZxTURPTGJncE5FTFE0cnc1elRMdVNDSEtTd20ifQ.Mjn0s0ew1srMJCb5Yfe_RsWeNV41Cc7PMPI4yXhqajc',
  }
}